### ISSUE TITLE
API analysis for Quil fails

### ISSUE THREAD

**Issue by anthonygalea** [cljdoc/cljdoc#274]
Just noticed that the docs for [quil](https://github.com/quil/quil) are incomplete on [cljdoc](https://cljdoc.org/d/quil/quil/2.8.0/doc/readme). Only the readme is present.

Tried to run cljdoc locally and [ingest from local sources](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md#importing-a-project-from-local-sources) to check if something went wrong during the build, but I cannot decipher what's wrong from the output. Any advice on how to get more information of what could have gone wrong?

```
╭─anthony@avalon ~/Desktop/cljdoc  ‹master›  13:28:09
╰─$ ./script/cljdoc ingest -p quil/quil -v 2.8.0 --git ~/Desktop/quil/quil-master                                                                                                                         255 ↵
INFO [2019-02-10 13:29:05,508] main - cljdoc.server.system Starting :cljdoc/build-tracker
INFO [2019-02-10 13:29:05,513] main - cljdoc.server.system Starting :cljdoc/storage
INFO [2019-02-10 13:29:05,517] main - cljdoc.server.system Starting :cljdoc/analysis-service nil
INFO [2019-02-10 13:29:05,833] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Cloning Git repo {:url /Users/anthony/Desktop/quil/quil-master :revision 9e7b6a64d35150292335fc80d9ac79d0d32936be}
INFO [2019-02-10 13:29:07,793] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Analyzing at revision: 9e7b6a64d35150292335fc80d9ac79d0d32936be
INFO [2019-02-10 13:29:07,935] clojure-agent-send-off-pool-0 - cljdoc.server.ingest Importing Articles /Users/anthony/Desktop/quil/quil-master 9e7b6a64d35150292335fc80d9ac79d0d32936be
INFO [2019-02-10 13:29:07,974] clojure-agent-send-off-pool-1 - cljdoc.analysis.service Starting local analysis for quil/quil 2.8.0 /Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.jar
INFO [2019-02-10 13:30:01,513] clojure-agent-send-off-pool-0 - cljdoc.analysis.service Got file from Local AnalysisService /tmp/cljdoc/analysis-out/cljdoc-edn/quil/quil/2.8.0/cljdoc.edn
ERROR [2019-02-10 13:30:01,520] clojure-agent-send-off-pool-0 - cljdoc.analysis.service {:project "quil/quil",
 :version "2.8.0",
 :jarpath
 "/Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.jar",
 :pompath
 "/Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.pom",
 :repos
 {"clojars" {:url "https://repo.clojars.org/"},
  "central" {:url "http://central.maven.org/maven2/"}}}
/Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.pom {clojars {:url https://repo.clojars.org/}, central {:url http://central.maven.org/maven2/}}

clojure.lang.ExceptionInfo: Analysis with local AnalysisService failed
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at cljdoc.analysis.service.Local.wait_for_build(service.clj:146)
	at cljdoc.server.api$analyze_and_import_api_BANG_.invokeStatic(api.clj:29)
	at cljdoc.server.api$analyze_and_import_api_BANG_.invoke(api.clj:10)
	at cljdoc.server.api$kick_off_build_BANG_$fn__27098.invoke(api.clj:75)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinklepsch** [comment]
Hey Anthony! Thanks for opening this issue :) 

I re-ran the build for quil and it seems there is a dependency issue. The full logs can be found here https://circleci.com/gh/cljdoc/builder/1618

I've seen dependency problems with some specific versions of bouncy castle before but can't specifically remember what the fix was. I think some artefact got renamed or similar.

Sorry the local ingest didn't provide a more useful error message, I'll try to remember to look into this and ensure that the actual cause is surfaced properly. 

Once that's done I'll ping you again and maybe you can help us get to the bottom of this or make some adjustments to Quil to avoid this issue altogether.

**Comment by martinklepsch** [comment]
Hey again Anthony! I just pushed a commit that should improve how errors around analysis are surfaced when running the analysis locally. If you pull `master` and try your command again you should be able to very clearly see that the issue is related to some bouncycastle dependency not being available. 

``` 
Could not find artifact bouncycastle:bctsp-jdk14:jar:138
```

Note that this plain `clj` invocation also fails for the same reason: 

```
clj -Sdeps '{:deps {quil {:mvn/version "2.8.0"}}}' -Stree
```

I didn't yet have time to look into what dependency is pulling in this old bouncy castle version. If you'd like to help investigate this further that would be super helpful!

**Comment by anthonygalea** [comment]
Hi Martin, thanks for looking into this and rerunning the build. Eventually managed to run the ingest from local sources successfully:

<img width="1792" alt="screenshot" src="https://user-images.githubusercontent.com/1301852/52631551-5d45d680-2ebf-11e9-9be1-7cd5ab80e3d0.png">

### Background

Found issues with similar symptoms in the [quil](https://github.com/quil/quil/issues/247) and [incanter](https://github.com/incanter/incanter/issues/388) repos. There is an [issue](https://dev.clojure.org/jira/browse/TDEPS-8) reported in the clojure jira that tools.deps does not handle maven relocations. Looked briefly into the cljdoc source and if I understood correctly cljdoc is using the tools.deps library to fetch dependencies so it seemed this had same root cause.

### Approach to get ingest working

I found a [commit in incanter](https://github.com/incanter/incanter/commit/af22d8fc7e8dc7a05e8bd8661671bf630f9fc81a) where the bouncycastle dependency was excluded and a dependency on the relocated version was added. Seems this commit did not resolve the issue because running `clj -Sdeps '{:deps {incanter {:mvn/version "1.9.3"}}}'` still fails. But luckily I took a closer look and noticed the exclusion was for `org.bouncycastle/bctsp-jdk14` while the artifact that couldn't be fetched is `bouncycastle/bctsp-jdk14` (notice no org in the group id) So I tried the following change in a local fork of quil:

```clj
-                 [com.lowagie/itext "2.1.7"]
+                 [com.lowagie/itext "2.1.7"
+                  :exclusions [bouncycastle/bctsp-jdk14]]
+                 [org.bouncycastle/bctsp-jdk14 "1.38"]
```

After that:

```sh
# to install the snapshot in the local repo
lein install

# run ingest with snapshot
./script/cljdoc ingest -p quil/quil -v 3.0.0-SNAPSHOT --git ~/Desktop/quil/forks/quil
INFO [2019-02-12 11:39:20,629] main - cljdoc.server.system Starting :cljdoc/build-tracker
INFO [2019-02-12 11:39:20,635] main - cljdoc.server.system Starting :cljdoc/storage
INFO [2019-02-12 11:39:20,638] main - cljdoc.server.system Starting :cljdoc/analysis-service nil
INFO [2019-02-12 11:39:20,916] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Cloning Git repo {:url /Users/anthony/Desktop/quil/forks/quil :revision 258206d885e7c3d90b4e442b90659d6db46b9b44}
INFO [2019-02-12 11:39:23,667] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Analyzing at revision: 258206d885e7c3d90b4e442b90659d6db46b9b44
INFO [2019-02-12 11:39:23,777] clojure-agent-send-off-pool-0 - cljdoc.server.ingest Importing Articles /Users/anthony/Desktop/quil/forks/quil 258206d885e7c3d90b4e442b90659d6db46b9b44
INFO [2019-02-12 11:39:23,821] clojure-agent-send-off-pool-1 - cljdoc.analysis.service Starting local analysis for quil/quil 3.0.0-SNAPSHOT /Users/anthony/.m2/repository/quil/quil/3.0.0-SNAPSHOT/quil-3.0.0-SNAPSHOT.jar
INFO [2019-02-12 11:40:07,427] clojure-agent-send-off-pool-0 - cljdoc.analysis.service Got file from Local AnalysisService /tmp/cljdoc/analysis-out/cljdoc-edn/quil/quil/3.0.0-SNAPSHOT/cljdoc.edn
INFO [2019-02-12 11:40:07,497] clojure-agent-send-off-pool-0 - cljdoc.server.ingest Verifying cljdoc-edn contents against spec
INFO [2019-02-12 11:40:07,498] clojure-agent-send-off-pool-0 - cljdoc.server.ingest Importing API into database quil/quil 3.0.0-SNAPSHOT
INFO [2019-02-12 11:40:07,510] clojure-agent-send-off-pool-0 - cljdoc.storage.sqlite-impl version-id 2
```

What do you think about this approach?

Great work on cljdoc by the way :+1:

**Comment by anthonygalea** [comment]
Sorry @martinklepsch somehow just saw your second comment. Will try it out and paste output here.

**Comment by anthonygalea** [comment]
Yep looks good, thanks:

```sh
╭─anthony@avalon ~/Desktop/cljdoc  ‹master›  12:26:47
╰─$ ./script/cljdoc ingest -p quil/quil -v 2.8.0 --git ~/Desktop/quil/quil-master                                                                                                                         141 ↵
INFO [2019-02-12 12:27:20,623] main - cljdoc.server.system Starting :cljdoc/build-tracker
INFO [2019-02-12 12:27:20,627] main - cljdoc.server.system Starting :cljdoc/storage
INFO [2019-02-12 12:27:20,628] main - cljdoc.server.system Starting :cljdoc/analysis-service nil
INFO [2019-02-12 12:27:20,916] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Cloning Git repo {:url /Users/anthony/Desktop/quil/quil-master :revision 9e7b6a64d35150292335fc80d9ac79d0d32936be}
INFO [2019-02-12 12:27:22,810] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Analyzing at revision: 9e7b6a64d35150292335fc80d9ac79d0d32936be
INFO [2019-02-12 12:27:22,942] clojure-agent-send-off-pool-0 - cljdoc.server.ingest Importing Articles /Users/anthony/Desktop/quil/quil-master 9e7b6a64d35150292335fc80d9ac79d0d32936be
INFO [2019-02-12 12:27:22,979] clojure-agent-send-off-pool-1 - cljdoc.analysis.service Starting local analysis for quil/quil 2.8.0 /Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.jar
INFO [2019-02-12 12:27:31,093] clojure-agent-send-off-pool-0 - cljdoc.analysis.service Got file from Local AnalysisService /tmp/cljdoc/analysis-out/cljdoc-edn/quil/quil/2.8.0/cljdoc.edn
ERROR Analysis with local AnalysisService failed
STDOUT -----------------------------------------------------
{:project "quil/quil",
 :version "2.8.0",
 :jarpath
 "/Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.jar",
 :pompath
 "/Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.pom",
 :repos
 {"clojars" {:url "https://repo.clojars.org/"},
  "central" {:url "http://central.maven.org/maven2/"}}}
/Users/anthony/.m2/repository/quil/quil/2.8.0/quil-2.8.0.pom {clojars {:url https://repo.clojars.org/}, central {:url http://central.maven.org/maven2/}}

STDERR -----------------------------------------------------
clojure.lang.ExceptionInfo: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (http://central.maven.org/maven2/) {:lib bouncycastle/bctsp-jdk14, :coord {:mvn/version "138", :deps/manifest :mvn}}
	at clojure.tools.deps.alpha.extensions.maven$get_artifact.invokeStatic(maven.clj:102)
	at clojure.tools.deps.alpha.extensions.maven$get_artifact.invoke(maven.clj:90)
	at clojure.tools.deps.alpha.extensions.maven$eval722$fn__724.invoke(maven.clj:110)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$lib_paths$fn__1085.invoke(alpha.clj:211)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8125.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8125.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at clojure.tools.deps.alpha$lib_paths.invokeStatic(alpha.clj:207)
	at clojure.tools.deps.alpha$lib_paths.invoke(alpha.clj:205)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:237)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:218)
	at cljdoc.analysis.deps$resolved_and_cp.invokeStatic(deps.clj:110)
	at cljdoc.analysis.deps$resolved_and_cp.invoke(deps.clj:104)
	at cljdoc.analysis.runner_ng$_main.invokeStatic(runner_ng.clj:21)
	at cljdoc.analysis.runner_ng$_main.invoke(runner_ng.clj:15)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

**Comment by martinklepsch** [comment]
@anthonygalea yes that approach looks exactly like what I would have expected the solution to be (exclusions/dependency tweaks). 

Thanks for taking the time to investigate this 🙌

**Comment by martinklepsch** [comment]
@anthonygalea I think to really fix this we'll also need a new Quil release with an updated `.pom` file that includes your dependency changes right?

**Comment by anthonygalea** [comment]
That's correct @martinklepsch. The fix was merged but a Quil release hasn't happened. I was planning to close the issue once a release is made and I can confirm that the analysis worked.

**Comment by martinklepsch** [comment]
Cool :+1: Should we bug quil maintainers into cutting a release? 😛

**Comment by anthonygalea** [comment]
Unless someone else needs this I wouldn't because:
1. maintainers are bugged enough already :)
2. I assume there will be a release as soon as the branch for [this issue](https://github.com/quil/quil/issues/255) is merged

**Comment by anthonygalea** [comment]
Closing as [snapshot](https://cljdoc.org/d/quil/quil/3.0.0-SNAPSHOT/doc/readme) already looks good. Thanks again for your support @martinklepsch

**Comment by martinklepsch** [comment]
Thanks @anthonygalea for your work on this as well as keeping the issue up to date! Much appreciated :)

(Also very good call on not requesting a new release, after I thought about it I totally agree :)
