### ISSUE TITLE
Honor project ClojureScript version

### ISSUE THREAD

**Issue by mfikes** [cljdoc/cljdoc#298]
When encountering code that depends on a var that is in a newer version of ClojureScript than that being used by cljdoc / codox, analysis fails.

For example, analysis is currently done using 1.10.339, but `cljs.spec.alpha/fn-sym` was [introduced](https://github.com/clojure/clojurescript/commit/20ba8ef9415b46c18172a59cfe63ad16d2a35a3c) with 1.10.439. Code referring to that particular var will currently fail analysis.

**Comment by martinklepsch** [comment]
@mfikes can you provide an example of a library that fails due to this? Thanks

**Comment by mfikes** [comment]
@martinklepsch Yeah, I can construct a minimal example. (This happens for Planck, and I could reduce it.) But, upon further thought, I don't know how cljdoc would even _know_ the ClojureScript version to use. Perhaps _that_ is the root of the problem and this ticket is invalid.

The only way I can think to solve it would be to put metadata somewhere akin to `doc/cljdoc.edn` to specify something like this. Perhaps this doesn't matter for projects that use conventional setups.

**Comment by martinklepsch** [comment]
If this happens for Planck that's enough information, no need for a minimal repro. 👍

**Comment by mfikes** [comment]
@martinklepsch This ticket could nevertheless be invalid without a minimal repro. The problem could be that I was testing it using `lein` and installing locally, and running cljdoc locally. Upon further thought, it isn't clear to me that this is a valid test, because in that scenario I don't see how cljdoc would know which version of ClojureScript to use.

**Comment by mfikes** [comment]
Minimal repro:

`project.clj`:

```clojure
(defproject cljdoc-298 "1.0.0"
  :dependencies [[org.clojure/clojurescript "1.10.520"]])
```

`src/foo/core.cljs`:

```clojure
(ns foo.core
 (:require [clojure.spec.alpha :as s])

#'s/fn-sym
```

Then, in project dir: `lein install`

Then, in local cljdoc instance:

```
$ script/cljdoc ingest -p cljdoc-298/cljdoc-298 -v 1.0.0 --jar ~/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.jar --pom ~/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.pom --git ~/Desktop/cljdoc-298 --rev "master"
INFO [2019-05-21 07:58:54,889] main - cljdoc.server.system Starting :cljdoc/build-tracker
INFO [2019-05-21 07:58:54,892] main - cljdoc.server.system Starting :cljdoc/storage
INFO [2019-05-21 07:58:54,893] main - cljdoc.server.system Starting :cljdoc/analysis-service nil
INFO [2019-05-21 07:58:55,053] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Cloning Git repo {:url /Users/mfikes/Desktop/cljdoc-298 :revision master}
WARN [2019-05-21 07:58:55,188] clojure-agent-send-off-pool-0 - cljdoc.server.api Error while processing cljdoc-298/cljdoc-298 1.0.0: {:type "invalid-remote", :msg "Invalid remote: origin"}
INFO [2019-05-21 07:58:55,193] clojure-agent-send-off-pool-1 - cljdoc.analysis.service Starting local analysis for cljdoc-298/cljdoc-298 1.0.0 /Users/mfikes/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.jar
INFO [2019-05-21 07:59:04,996] clojure-agent-send-off-pool-0 - cljdoc.analysis.service Got file from Local AnalysisService /tmp/cljdoc/analysis-out/cljdoc-edn/cljdoc-298/cljdoc-298/1.0.0/cljdoc.edn
ERROR Analysis with local AnalysisService failed
STDOUT -----------------------------------------------------
{:project "cljdoc-298/cljdoc-298",
 :version "1.0.0",
 :jarpath
 "/Users/mfikes/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.jar",
 :pompath
 "/Users/mfikes/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.pom",
 :repos
 {"clojars" {:url "https://repo.clojars.org/"},
  "central" {:url "http://central.maven.org/maven2/"}}}
/Users/mfikes/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.pom {clojars {:url https://repo.clojars.org/}, central {:url http://central.maven.org/maven2/}}
Used dependencies for analysis:
org.clojure/clojure 1.9.0
  org.clojure/core.specs.alpha 0.1.24
  org.clojure/spec.alpha 0.1.143
cljdoc-298 /Users/mfikes/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.jar
org.clojure/clojurescript 1.10.339
  org.clojure/data.json 0.2.6
  org.clojure/google-closure-library 0.0-20170809-b9c14c6b
    org.clojure/google-closure-library-third-party 0.0-20170809-b9c14c6b
  org.mozilla/rhino 1.7R5
  com.cognitect/transit-clj 0.8.309
    com.cognitect/transit-java 0.8.332
      commons-codec/commons-codec 1.10
      com.fasterxml.jackson.core/jackson-core 2.8.7
      org.msgpack/msgpack 0.6.12
        com.googlecode.json-simple/json-simple 1.1.1
        org.javassist/javassist 3.18.1-GA
  org.clojure/tools.reader 1.3.0-alpha3
  com.google.javascript/closure-compiler-unshaded v20180610
    com.google.errorprone/error_prone_annotations 2.0.18
    com.google.jsinterop/jsinterop-annotations 1.0.0
    com.google.javascript/closure-compiler-externs v20180610
    com.google.guava/guava 22.0
      org.codehaus.mojo/animal-sniffer-annotations 1.14
      com.google.j2objc/j2objc-annotations 1.1
    args4j/args4j 2.33
    com.google.protobuf/protobuf-java 3.0.2
    com.google.code.findbugs/jsr305 3.0.1
    com.google.code.gson/gson 2.7
javax.servlet/servlet-api 2.5
codox/codox https://github.com/cljdoc/codox e0cd269
  org.clojure/tools.namespace 0.2.11
---------------------------------------------------------------------------
Going to write analysis result to: /tmp/cljdoc/analysis-out/cljdoc-edn/cljdoc-298/cljdoc-298/1.0.0/cljdoc.edn
Analyzing cljdoc-298/cljdoc-298 clj
exit-code 0 ---------------------------------------------------------------
stdout --------------------------------------------------------------------
Args:
  - namespaces: "nil"
  - jar-contents-path: "/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-cljdoc-298-cljdoc-298-1.0.01993235692781393943/contents"
  - platf: "clj"
  - file: "/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-298-cljdoc-2987880055143729752431.edn"
Analysing sources for platform "clj"
Clojure version 1.9.0
ClojureScript version 1.10.339
Codox opts: {:language :clojure, :root-path "/private/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T", :source-paths ["/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-cljdoc-298-cljdoc-298-1.0.01993235692781393943/contents"], :namespaces :all, :exception-handler #object[cljdoc.analysis.impl$codox_config$ex_handler__980 0xae202c6 "cljdoc.analysis.impl$codox_config$ex_handler__980@ae202c6"], :metadata {}, :writer clojure.core/identity, :exclude-vars #"^(map)?->\p{Upper}"}
Writing /var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-298-cljdoc-2987880055143729752431.edn

---------------------------------------------------------------------------
Analyzing cljdoc-298/cljdoc-298 cljs
exit-code 1 ---------------------------------------------------------------
stdout --------------------------------------------------------------------
Args:
  - namespaces: "nil"
  - jar-contents-path: "/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-cljdoc-298-cljdoc-298-1.0.01993235692781393943/contents"
  - platf: "cljs"
  - file: "/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-298-cljdoc-2989194610780330779251.edn"
Analysing sources for platform "cljs"
Clojure version 1.9.0
ClojureScript version 1.10.339
Codox opts: {:language :clojurescript, :root-path "/private/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T", :source-paths ["/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-cljdoc-298-cljdoc-298-1.0.01993235692781393943/contents"], :namespaces :all, :exception-handler #object[cljdoc.analysis.impl$codox_config$ex_handler__980 0x1a96d94c "cljdoc.analysis.impl$codox_config$ex_handler__980@1a96d94c"], :metadata {}, :writer clojure.core/identity, :exclude-vars #"^(map)?->\p{Upper}"}

---------------------------------------------------------------------------
stderr --------------------------------------------------------------------
Exception in thread "main" clojure.lang.ExceptionInfo: Could not analyze foo/core.cljs {}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at cljdoc.analysis.impl$codox_config$ex_handler__980.invoke(impl.clj:21)
	at codox.reader.clojurescript$read_file.invokeStatic(clojurescript.clj:95)
	at codox.reader.clojurescript$read_file.invoke(clojurescript.clj:83)
	at codox.reader.clojurescript$read_namespaces$fn__874$file_reader__875.invoke(clojurescript.clj:133)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$apply.invoke(core.clj:652)
	at codox.reader.clojurescript$read_namespaces$fn__874.invoke(clojurescript.clj:136)
	at clojure.core$map$fn__5587.invoke(core.clj:2745)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$mapcat.invokeStatic(core.clj:2775)
	at clojure.core$mapcat.doInvoke(core.clj:2775)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at codox.reader.clojurescript$read_namespaces.invokeStatic(clojurescript.clj:131)
	at codox.reader.clojurescript$read_namespaces.invoke(clojurescript.clj:105)
	at codox.main$read_namespaces.invokeStatic(main.clj:65)
	at codox.main$read_namespaces.invoke(main.clj:62)
	at codox.main$generate_docs.invokeStatic(main.clj:105)
	at codox.main$generate_docs.invoke(main.clj:98)
	at cljdoc.analysis.impl$codox_namespaces.invokeStatic(impl.clj:50)
	at cljdoc.analysis.impl$codox_namespaces.invoke(impl.clj:43)
	at cljdoc.analysis.impl$_main.invokeStatic(impl.clj:60)
	at cljdoc.analysis.impl$_main.invoke(impl.clj:57)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: /var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-cljdoc-298-cljdoc-298-1.0.01993235692781393943/contents/foo/core.cljs [line 5, col 1] Unexpected EOF while reading item 4 of list, starting at line 1 and column 1. {:type :reader-exception, :ex-kind :eof, :file "/var/folders/bq/fkn759wj5qxc85s3kch20dmr0000gn/T/cljdoc-cljdoc-298-cljdoc-298-1.0.01993235692781393943/contents/foo/core.cljs", :line 5, :col 1}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at clojure.tools.reader.impl.errors$throw_ex.invokeStatic(errors.clj:34)
	at clojure.tools.reader.impl.errors$throw_ex.doInvoke(errors.clj:24)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.tools.reader.impl.errors$eof_error.invokeStatic(errors.clj:46)
	at clojure.tools.reader.impl.errors$eof_error.doInvoke(errors.clj:42)
	at clojure.lang.RestFn.invoke(RestFn.java:516)
	at clojure.tools.reader.impl.errors$throw_eof_delimited.invokeStatic(errors.clj:57)
	at clojure.tools.reader.impl.errors$throw_eof_delimited.invoke(errors.clj:54)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:201)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:190)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:924)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:906)
	at clojure.tools.reader$read.invokeStatic(reader.clj:977)
	at clojure.tools.reader$read.invoke(reader.clj:950)
	at cljs.analyzer$forms_seq_STAR_$forms_seq___2548$fn__2549$fn__2550.invoke(analyzer.cljc:3705)
	at cljs.analyzer$forms_seq_STAR_$forms_seq___2548$fn__2549.invoke(analyzer.cljc:3698)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$seq__5124.invoke(core.clj:137)
	at cljs.analyzer$parse_ns$fn__2564.invoke(analyzer.cljc:3807)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:3774)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:3753)
	at cljs.analyzer.api$parse_ns.invokeStatic(api.cljc:118)
	at cljs.analyzer.api$parse_ns.invoke(api.cljc:97)
	at cljs.analyzer.api$parse_ns.invokeStatic(api.cljc:110)
	at cljs.analyzer.api$parse_ns.invoke(api.cljc:97)
	at cljs.analyzer.api$parse_ns.invokeStatic(api.cljc:107)
	at cljs.analyzer.api$parse_ns.invoke(api.cljc:97)
	at codox.reader.clojurescript$read_file.invokeStatic(clojurescript.clj:86)
	... 40 more

---------------------------------------------------------------------------
Analysis failed with code 1

STDERR -----------------------------------------------------
```

Note, in the above, it indicates it is using ClojureScript version 1.10.339. The `project.clj` and the source, on the other hand are using 1.10.520.
