### ISSUE TITLE
Unable to generate docs for private clojure project locally

### ISSUE THREAD

**Issue by pntripathi9417** [cljdoc/cljdoc#358]
I am trying to generate docs for a personal ClojureScript project locally, but after following the guideline I end up with following errors:

```
INFO [2019-10-23 10:03:19,674] main - cljdoc.server.system Starting :cljdoc/build-tracker
INFO [2019-10-23 10:03:19,682] main - cljdoc.server.system Starting :cljdoc/storage
INFO [2019-10-23 10:03:19,683] main - cljdoc.server.system Starting :cljdoc/analysis-service nil
INFO [2019-10-23 10:03:21,109] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Cloning Git repo {:url /Users/circle/Project/vadelabs/vade-design-system :revision 4f37d65f5aafd0df12060f4f30b7d59eb8a440b4}
INFO [2019-10-23 10:03:22,359] clojure-agent-send-off-pool-0 - cljdoc.analysis.git Analyzing at revision: 4f37d65f5aafd0df12060f4f30b7d59eb8a440b4
INFO [2019-10-23 10:03:22,607] clojure-agent-send-off-pool-0 - cljdoc.server.ingest Importing Articles ../../vade-design-system 4f37d65f5aafd0df12060f4f30b7d59eb8a440b4
INFO [2019-10-23 10:03:22,656] clojure-agent-send-off-pool-1 - cljdoc.analysis.service Starting local analysis for vadelabs/vade-design-system 0.0.0-SNAPSHOT https://repo.clojars.org/vadelabs/vade-design-system/0.0.0-SNAPSHOT/vade-design-system-0.0.0-20191022.120618-1.jar
INFO [2019-10-23 10:05:12,501] clojure-agent-send-off-pool-0 - cljdoc.analysis.service Got file from Local AnalysisService /tmp/cljdoc/analysis-out/cljdoc-edn/vadelabs/vade-design-system/0.0.0-SNAPSHOT/cljdoc.edn
ERROR Analysis with local AnalysisService failed
STDOUT -----------------------------------------------------
{:project "vadelabs/vade-design-system",
 :version "0.0.0-SNAPSHOT",
 :jarpath
 "https://repo.clojars.org/vadelabs/vade-design-system/0.0.0-SNAPSHOT/vade-design-system-0.0.0-20191022.120618-1.jar",
 :pompath
 "https://repo.clojars.org/vadelabs/vade-design-system/0.0.0-SNAPSHOT/vade-design-system-0.0.0-20191022.120618-1.pom",
 :repos
 {"clojars" {:url "https://repo.clojars.org/"},
  "central" {:url "http://central.maven.org/maven2/"}}}
Downloading remote jar...
https://repo.clojars.org/vadelabs/vade-design-system/0.0.0-SNAPSHOT/vade-design-system-0.0.0-20191022.120618-1.pom {clojars {:url https://repo.clojars.org/}, central {:url http://central.maven.org/maven2/}}
Used dependencies for analysis:
org.clojure/clojure 1.10.1
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.176
org.clojure/clojurescript 1.10.520
  org.clojure/data.json 0.2.6
  org.clojure/google-closure-library 0.0-20170809-b9c14c6b
    org.clojure/google-closure-library-third-party 0.0-20170809-b9c14c6b
  org.mozilla/rhino 1.7R5
  com.google.javascript/closure-compiler-unshaded v20180805
    com.google.jsinterop/jsinterop-annotations 1.0.0
    com.google.javascript/closure-compiler-externs v20180805
    com.google.guava/guava 25.1-jre
      com.google.errorprone/error_prone_annotations 2.1.3
      org.codehaus.mojo/animal-sniffer-annotations 1.14
      com.google.j2objc/j2objc-annotations 1.1
      org.checkerframework/checker-qual 2.0.0
      com.google.code.findbugs/jsr305 3.0.2
    args4j/args4j 2.0.26
    com.google.protobuf/protobuf-java 3.0.2
    com.google.code.gson/gson 2.7
vadelabs/vade-design-system /private/var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T/cljdoc-vadelabs-vade-design-system-0.0.0-SNAPSHOT1834781954659284829/downloaded.jar
  stylefy/stylefy 1.14.0
    prismatic/dommy 1.1.0
    javax.xml.bind/jaxb-api 2.4.0-b180830.0359
      javax.activation/javax.activation-api 1.2.0
  day8.re-frame/http-fx 0.1.6
  nubank/workspaces 1.0.13
    fulcrologic/fulcro-inspect 2.2.4
      com.wsscode/pathom 2.2.0-beta4
        spec-coerce/spec-coerce 1.0.0-alpha6
        com.wsscode/spec-inspec 1.0.0-alpha2
        org.clojure/math.combinatorics 0.1.4
        camel-snake-kebab/camel-snake-kebab 0.4.0
    cljsjs/highlight 9.12.0-2
    fulcrologic/fulcro 2.6.16
      clojure-future-spec/clojure-future-spec 1.9.0-beta4
      com.stuartsierra/component 0.3.2
        com.stuartsierra/dependency 0.2.0
    com.fulcrologic/fulcro 3.0.5
      edn-query-language/eql 0.0.8
      com.taoensso/encore 2.115.0
        com.taoensso/truss 1.5.0
        org.clojure/tools.reader 1.3.2
      gnl/ghostwheel 0.3.9
        expound/expound 0.7.2
        gnl/ghostwheel.logging 0.3.9
        orchestra/orchestra 2019.02.06-1
        gnl/ghostwheel.unghost 0.3.9
        org.clojure/test.check 0.10.0-alpha4
      com.cognitect/transit-cljs 0.8.256
        com.cognitect/transit-js 0.8.846
      com.taoensso/timbre 4.10.0
        io.aviso/pretty 0.1.33
      com.cognitect/transit-clj 0.8.313
        com.cognitect/transit-java 0.8.337
          commons-codec/commons-codec 1.10
          com.fasterxml.jackson.core/jackson-core 2.8.7
          org.msgpack/msgpack 0.6.12
            com.googlecode.json-simple/json-simple 1.1.1
            org.javassist/javassist 3.18.1-GA
    cljsjs/react-grid-layout 0.16.6-0
    fulcrologic/fulcro-incubator 0.0.19
    com.wsscode/fuzzy 1.0.0
    com.fulcrologic/fulcro-garden-css 3.0.6
      garden/garden 1.3.9
    org.clojure/core.async 0.4.474
      org.clojure/tools.analyzer.jvm 0.7.0
        org.clojure/tools.analyzer 0.6.9
        org.clojure/core.memoize 0.5.9
          org.clojure/core.cache 0.6.5
            org.clojure/data.priority-map 0.0.7
        org.ow2.asm/asm-all 4.2
  kibu/pushy 0.3.8
  cljs-ajax/cljs-ajax 0.7.3
    org.apache.httpcomponents/httpasyncclient 4.1.3
      org.apache.httpcomponents/httpcore-nio 4.4.6
      commons-logging/commons-logging 1.2
      org.apache.httpcomponents/httpclient 4.5.3
    net.colourcoding/poppea 0.2.1
    org.apache.httpcomponents/httpcore 4.4.6
    cheshire/cheshire 5.7.1
      com.fasterxml.jackson.dataformat/jackson-dataformat-cbor 2.8.6
      tigris/tigris 0.1.1
      com.fasterxml.jackson.dataformat/jackson-dataformat-smile 2.8.6
  day8.re-frame/tracing 0.5.1
  binaryage/devtools 0.9.10
    binaryage/env-config 0.2.2
  re-frame/re-frame 0.11.0-rc1
    org.clojure/tools.logging 0.4.1
    net.cgrand/macrovich 0.2.1
  reagent/reagent 0.9.0-rc2
    cljsjs/react-dom 16.9.0-0
    cljsjs/react 16.9.0-0
    cljsjs/react-dom-server 16.9.0-0
  cider/cider-nrepl 0.21.0
    nrepl/nrepl 0.6.0
  com.andrewmcveigh/cljs-time 0.5.2
  proto-repl/proto-repl 0.3.1
    compliment/compliment 0.2.7
      defprecated/defprecated 0.1.3
  bidi/bidi 2.1.6
    prismatic/schema 1.1.7
  day8.re-frame/re-frame-10x 0.4.4
    cljsjs/react-highlight 1.0.7-2
      cljsjs/prop-types 15.6.0-0
    com.yahoo.platform.yui/yuicompressor 2.4.8
    zprint/zprint 0.4.16
      rewrite-clj/rewrite-clj 0.6.1
      rewrite-cljs/rewrite-cljs 0.4.4
    cljsjs/react-flip-move 3.0.1-1
    cljsjs/create-react-class 15.6.3-1
javax.servlet/javax.servlet-api 4.0.1
codox/codox https://github.com/cljdoc/codox e0cd269
  org.clojure/tools.namespace 0.2.11
---------------------------------------------------------------------------
Going to write analysis result to: /tmp/cljdoc/analysis-out/cljdoc-edn/vadelabs/vade-design-system/0.0.0-SNAPSHOT/cljdoc.edn
Analyzing vadelabs/vade-design-system clj
exit-code 0 ---------------------------------------------------------------
stdout --------------------------------------------------------------------
Args:
  - namespaces: "nil"
  - jar-contents-path: "/var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T/cljdoc-vadelabs-vade-design-system-0.0.0-SNAPSHOT1834781954659284829/contents"
  - platf: "clj"
  - file: "/var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T/vadelabs-vade-design-system5378110709178632880.edn"
Analysing sources for platform "clj"
Clojure version 1.10.1
ClojureScript version 1.10.520
Codox opts: {:language :clojure, :root-path "/private/var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T", :source-paths ["/var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T/cljdoc-vadelabs-vade-design-system-0.0.0-SNAPSHOT1834781954659284829/contents"], :namespaces :all, :exception-handler #object[cljdoc.analysis.impl$codox_config$ex_handler__971 0x4fb392c4 "cljdoc.analysis.impl$codox_config$ex_handler__971@4fb392c4"], :metadata {}, :writer clojure.core/identity, :exclude-vars #"^(map)?->\p{Upper}"}
Writing /var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T/vadelabs-vade-design-system5378110709178632880.edn

---------------------------------------------------------------------------
Analyzing vadelabs/vade-design-system cljs
exit-code 1 ---------------------------------------------------------------
stdout --------------------------------------------------------------------

---------------------------------------------------------------------------
stderr --------------------------------------------------------------------
Execution error (AssertionError) at cljdoc.analysis.impl/sanitize-cdx (impl.clj:30).
Assert failed: (:name cdx-namespace)

Full report at:
/var/folders/9j/qg_n2h690txfbm7pttd86k6m0000gn/T/clojure-2523026066558512230.edn

---------------------------------------------------------------------------
Analysis failed with code 1

STDERR -----------------------------------------------------

ERROR [2019-10-23 10:05:12,539] clojure-agent-send-off-pool-0 - cljdoc.server.api analysis job failed for project: vadelabs/vade-design-system, version: 0.0.0-SNAPSHOT, build-id: 2
clojure.lang.ExceptionInfo: Analysis with local AnalysisService failed
	at cljdoc.analysis.service.Local.wait_for_build(service.clj:151)
	at cljdoc.server.api$analyze_and_import_api_BANG_.invokeStatic(api.clj:29)
	at cljdoc.server.api$analyze_and_import_api_BANG_.invoke(api.clj:10)
	at cljdoc.server.api$kick_off_build_BANG_$fn__29503.invoke(api.clj:77)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

As I am a beginner and trying to learn ClojureScript, I am unable to figure out what could be the issue.

**Comment by martinklepsch** [comment]
Hey Pragyan! Is the source for this available somewhere? It seems that something is tripping up the ClojureScript analysis but it's hard to tell what specifically without looking at the code. Feel free to share privately (Slack, email, Twitter) as well.

**Comment by pntripathi9417** [comment]
I have mailed you the zipped folder at martinklepsch@googlemail.com

**Comment by pntripathi9417** [comment]
seems like `cljdoc` uses `codox` to generate docs. It is passing following options for `codox`:

```
Codox opts: {:language :clojure, :root-path "/tmp", :source-paths ["/tmp/cljdoc-com.vadelabs-vds-0.0.0-SNAPSHOT4962549712162603683/contents"], :namespaces :all, :exception-handler #object[cljdoc.analysis.impl$codox_config$ex_handler__971 0x1e1b061 "cljdoc.analysis.impl$codox_config$ex_handler__971@1e1b061"], :metadata {}, :writer clojure.core/identity, :exclude-vars #"^(map)?->\p{Upper}"}
Writing /tmp/com.vadelabs-vds4431438073395435530.edn
```

When I directly use `codox`, passing `{:language :clojure}` does not work. Instead my `codox` configuration looks like the following: 
```
:codox {:output-path "doc"
          :language :clojurescript
          :source-paths ["src"]
          :metadata {:doc/format :markdown}}
```

Any idea how can we change `codox` configuration in `cljdoc`?

**Comment by martinklepsch** [comment]
I've received your code but haven't had time for much more than a cursory look, sorry! 

cljdoc will determine the languages to use based on what files are present in the jar. While this is not in production yet I'd suggest you try @lread's factored-out [`cljdoc-analyzer`](https://github.com/cljdoc/cljdoc-analyzer) ([general usage instructions](https://github.com/cljdoc/cljdoc-analyzer#general-use)).

Generally it seems that the analyzer somehow returns a namespace that does not have a name which is obviously broken. Instead of changing the configuration I think it would be great if we could understand and fix the underlying issue.

**Comment by pntripathi9417** [comment]
When I run the following command:

```
clojure -m cljdoc-analyzer.cljdoc-main '{:project "com.vadelabs/vds", :version "0.0.0-SNAPSHOT", :jarpath "/Users/circle/.m2/repository/com/vadelabs/vds/0.0.0-SNAPSHOT/vds-0.0.0-SNAPSHOT.jar", :pompath "/Users/circle/.m2/repository/com/vadelabs/vds/0.0.0-SNAPSHOT/vds-0.0.0-SNAPSHOT.pom", :repos {"clojars" {:url "https://repo.clojars.org/"}, "central" {:url "http://central.maven.org/maven2/"}}}'
```

I get this error:

```
2019-10-25 16:34:50,900 ERROR cljdoc-analyzer.runner - Analysis failed
clojure.lang.ExceptionInfo: Spec assertion failed
{:publics ()} - failed: (contains? % :name) in: [:analysis "cljs" 1 0] at: [:analysis 1] spec: :cljdoc.analysis/namespace

	at clojure.spec.alpha$assert_STAR_.invokeStatic(alpha.clj:1966)
	at clojure.spec.alpha$assert_STAR_.invoke(alpha.clj:1959)
	at cljdoc_analyzer.spec$assert.invokeStatic(spec.cljc:55)
	at cljdoc_analyzer.spec$assert.invoke(spec.cljc:53)
	at cljdoc_analyzer.runner$validate_result.invokeStatic(runner.clj:140)
	at cljdoc_analyzer.runner$validate_result.invoke(runner.clj:139)
	at cljdoc_analyzer.runner$get_metadata_STAR_.invokeStatic(runner.clj:175)
	at cljdoc_analyzer.runner$get_metadata_STAR_.invoke(runner.clj:150)
	at cljdoc_analyzer.runner$get_metadata.invokeStatic(runner.clj:192)
	at cljdoc_analyzer.runner$get_metadata.invoke(runner.clj:179)
	at cljdoc_analyzer.runner$analyze_BANG_.invokeStatic(runner.clj:214)
	at cljdoc_analyzer.runner$analyze_BANG_.invoke(runner.clj:197)
	at cljdoc_analyzer.cljdoc_main$_main.invokeStatic(cljdoc_main.clj:26)
	at cljdoc_analyzer.cljdoc_main$_main.invoke(cljdoc_main.clj:22)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```

Any ideas what could be causing this spec assertion failure?

**Comment by lread** [comment]
A case of a missing namespace, interesting!  I have some time to have a peek at this issue.

I'll ping you at your github email address.  If you reply with your code, I can take a look.

**Comment by pntripathi9417** [comment]
@lread Thanks a lot. I have mailed you the source code. Please let me know if anything else is needed.

**Comment by lread** [comment]
Got your code @pntripathi9417, and am able to reproduce your issue on my development box.
I shall dig in and let you know what I find.

**Comment by lread** [comment]
I found the cause @pntripathi9417.  

Under `src/vds/ions` there is an empty `core.cljs`.  After deleting the empty `core.cljs` file, cljdoc-analyzer successfully processed your jar file.

Notes:
1. Generated and locally installed your jar from your project root dir via: `lein install`
2. Tested with cljdoc-analyzer via:

        clojure -m cljdoc-analyzer.main analyze \
          --project vadelabs/vade-design-system --version 0.0.0-SNAPSHOT \
          --output-filename vade-test.edn

**Comment by pntripathi9417** [comment]
@lread Thanks a lot. I went through the code base of the `cljdoc-analyzer` but could not pinpoint the exact issue. Thanks a lot for the help. It seems to be working now. 👍
