### ISSUE TITLE
DOC Dependency to CLI tool

### ISSUE THREAD

**Issue by frozar** [cljdoc/cljdoc#381]
I'm still a beginner in the Clojure world, and I was following the setup for [Running cljdoc locally](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md). When I arrived at the command to launch the cljdoc server:
```sh
./script/cljdoc run
```
I got this weird error message:
```
Exception in thread "main" java.io.FileNotFoundException: -A:cli (Aucun fichier ou dossier de ce type)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at clojure.lang.Compiler.loadFile(Compiler.java:7449)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$script_opt.invokeStatic(main.clj:338)
	at clojure.main$script_opt.invoke(main.clj:333)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
```
After a while, I discover that I didn't use the CLI tool which is required to get cljdoc running.

This dependency should be explicit in the documentation page "Running cljdoc locally". As the [official documentation](https://clojure.org/guides/getting_started) which describes its installation is straightforward, a simple link to it will get the job done.

**Comment by martinklepsch** [comment]
Thanks, that's a great point @frozar. Would you like to open a PR for this?

**Comment by frozar** [comment]
Ok, I'll make a submission for this soon.
