### ISSUE TITLE
Better error page if article or namespace is missing

### ISSUE THREAD

**Issue by JoelSanchez** [cljdoc/cljdoc#50]
Right now it shows a stacktrace:
https://cljdoc.xyz/d/ventas/ventas/0.0.6/doc/documentation-index/

```
clojure.lang.ExceptionInfo: Error on GET {:response #yada.context.Response{:headers {}, :vary #{}, :produces {:media-type #yada.media_type.MediaTypeMap{:name "text/html", :type "text", :subtype "html", :parameters {}, :quality 1.0}}}, :resource yada.resource.Resource, :error #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [java.io.StringReader  "StringReader.java" 50]}]
 :trace
 [[java.io.StringReader  "StringReader.java" 50]
  [org.jsoup.parser.Parser parse "Parser.java" 107]
  [org.jsoup.Jsoup parse "Jsoup.java" 58]
  [cljdoc.util.fixref$fix invokeStatic "fixref.clj" 71]
  [cljdoc.util.fixref$fix invoke "fixref.clj" 66]
  [cljdoc.renderers.html$eval5773$fn__5775 invoke "html.clj" 83]
  [clojure.lang.MultiFn invoke "MultiFn.java" 238]
  [cljdoc.server.doc_pages.DocPage$page_response__22960 invoke "doc_pages.clj" 74]
  [yada.methods$apply_response_fn invokeStatic "methods.clj" 31]
  [yada.methods$apply_response_fn invoke "methods.clj" 30]
  [yada.methods$eval19575$fn__19582$fn__19587 invoke "methods.clj" 174]
  [manifold.deferred$eval6930$chain___6951 invoke "deferred.clj" 860]
  [clojure.lang.AFn applyToHelper "AFn.java" 165]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 661]
  [clojure.core$apply invoke "core.clj" 652]
  [manifold.deferred$eval6930$chain___6951$fn__6955 invoke "deferred.clj" 889]
  [manifold.deferred.Listener onSuccess "deferred.clj" 219]
  [manifold.deferred.Deferred$fn__6729 invoke "deferred.clj" 378]
  [clojure.lang.AFn run "AFn.java" 22]
  [io.aleph.dirigiste.Executor$Worker$1 run "Executor.java" 62]
  [manifold.executor$thread_factory$reify__6112$f__6113 invoke "executor.clj" 44]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 748]]}}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at yada.methods$eval19575$fn__19582$fn__19593.invoke(methods.clj:189)
	at manifold.deferred$catch_SINGLEQUOTE_$fn__6981.invoke(deferred.clj:963)
	at manifold.deferred.Listener.onError(deferred.clj:220)
	at manifold.deferred.Deferred$fn__6749$fn__6750.invoke(deferred.clj:399)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__6112$f__6113.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TimoKramer** [comment]
is this already solved?

**Comment by JoelSanchez** [comment]
Yep, now it shows a blank page:
https://cljdoc.xyz/d/ventas/ventas/0.0.6/doc/doesnotexist
(`documentation-index` exists now, so it isn't a good example anymore...)

**Comment by JoelSanchez** [comment]
Also good for the namespace case: https://cljdoc.xyz/d/ventas/doesnotexist/0.0.6/doc/documentation-index
